# Generated by Django 5.1.5 on 2025-02-27 16:55

import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0009_alter_ticket_asignado_a'),
    ]

    operations = [
        migrations.RenameField(
            model_name='administrador',
            old_name='username',
            new_name='usuario',
        ),
        migrations.AddField(
            model_name='usuario',
            name='cedula',
            field=models.IntegerField(default=0, primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(1)], verbose_name='CÃ©dula'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='imagen_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='perfiles/'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
    ]
